<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="DESKTOP-PMLFRNT" failures="1" tests="3" name="Tutninja" time="23.218" errors="0" timestamp="2023-10-17T20:12:43 IST">
  <testcase classname="TestCases.LoginTest" name="Login_with_valid_details" time="2.41">
    <failure type="java.lang.AssertionError" message="not login corretly expected [false] but found [true]">
      <![CDATA[java.lang.AssertionError: not login corretly expected [false] but found [true]
at TestCases.LoginTest.Login_with_valid_details(LoginTest.java:39)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at com.intellij.rt.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:66)
at com.intellij.rt.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:105)
... Removed 25 stack frames]]>
    </failure>
  </testcase> <!-- Login_with_valid_details -->
  <testcase classname="TestCases.LoginTest" name="Login_with_INvalid_details" time="2.265"/>
  <testcase classname="TestCases.LoginTest" name="Login_With_no_data" time="1.774"/>
</testsuite> <!-- Tutninja -->
